%% Timing relative 
drawFixTimeRel = drawFixTime - trialStartTime;
startedFixTimerRel = startedFixTimer - drawFixTime;
drawMemCueTimeRel = drawMemCueTime - startedFixTimer;
remMemCueTimeRel = remMemCueTime - drawMemCueTime;
drawSacTimeRel = drawSacTime - remMemCueTime;
waitFixTimeRel = waitFixTime - drawSacTime;
drawMemTestRel = drawMemTest - waitFixTime;
drawMasksRel = drawMasks - drawMemTest;
remMasksRel = remMasks - drawMasks;
startReportRel = startReport - remMasks;
madeClick3Rel = madeClick3 - madeClick2;
madeClick2Rel = madeClick2 - madeClick1;
madeClick1Rel = madeClick1 - startReport;

%% DATE
Date = datestr(date);
dt = datestr(now, 'mmmm dd, yyyy HH:MM:SS.FFF');

%% ASSIGN ET PARAMETERS IF NO ET
if ~ETconnected
    sac_duration = NaN;
    prefix_duration = NaN; 
    prefix_execution = NaN;
    sac_execution = NaN;
    et_good_check = NaN;
    et_null_check = NaN;
    et_total_check = NaN;
end

if practice == 1
Results(trial,:) = {...
    dt,...1
    subj_init,... 2
    subj_num,...  
    block,... 
    trial,...5
    grandTrial,...   
    saccade,...
    retino,...
    firstFix',... 
    newFix',...10   
    position,...
    memCueLoc,... 
    ffPos,... 
    nfPos,... 
    cueDist2ff,... 15
    cueDist2nf,... 
    PPD,...
    DPP,... 
    UL,...
    UR,... 20
    LL,...
    LR,...
    testColor,...
    reportedcolor,...
    col_diff,...25
    confValues,...
    confValues2,...
    startingcolor,...
    randrotate,...
    flip,... 30
    asymmetric,...
    trialStartTime,...  
    drawFixTimeRel,...
    startedFixTimerRel,...
    drawMemCueTimeRel,... 35
    remMemCueTimeRel,...
    drawSacTimeRel,...
    waitFixTimeRel,...
    drawMemTestRel,... 
    drawMasksRel,... 40
    remMasksRel,...
    startReportRel,...
    madeClick1Rel,...
    madeClick2Rel,...
    madeClick3Rel,... 45
    prefix_execution,...  
    prefix_duration,... 
    sac_execution,...
    sac_duration,...
    drawFixTime,...
    startedFixTimer,...
    drawMemCueTime,...
    remMemCueTime,...
    drawSacTime,...
    waitFixTime,...
    drawMemTest,...
    drawMasks,...
    remMasks,...
    startReport,...
    madeClick1,...
    madeClick2,...
    madeClick3,...
    et_good_check,...
    et_null_check,...
    et_total_check,...
    practice,...
    minDistanceIndex,...
    testingRoom};
else
Results(grandTrial,:) = {...
    dt,...1
    subj_init,... 2
    subj_num,...  
    block,... 
    trial,...5
    grandTrial,...   
    saccade,...
    retino,...
    firstFix',... 
    newFix',...10   
    position,...
    memCueLoc,... 
    ffPos,... 
    nfPos,... 
    cueDist2ff,... 15
    cueDist2nf,... 
    PPD,...
    DPP,... 
    UL,...
    UR,... 20
    LL,...
    LR,...
    testColor,...
    reportedcolor,...
    col_diff,...25
    confValues,...
    confValues2,...
    startingcolor,...
    randrotate,...
    flip,... 30
    asymmetric,...
    trialStartTime,...  
    drawFixTimeRel,...
    startedFixTimerRel,...
    drawMemCueTimeRel,... 35
    remMemCueTimeRel,...
    drawSacTimeRel,...
    waitFixTimeRel,...
    drawMemTestRel,... 
    drawMasksRel,... 40
    remMasksRel,...
    startReportRel,...
    madeClick1Rel,...
    madeClick2Rel,...
    madeClick3Rel,... 45
    prefix_execution,...  
    prefix_duration,... 
    sac_execution,...
    sac_duration,...
    drawFixTime,... 50
    startedFixTimer,...
    drawMemCueTime,...
    remMemCueTime,...
    drawSacTime,...
    waitFixTime,... 55
    drawMemTest,...
    drawMasks,...
    remMasks,...
    startReport,...
    madeClick1,... 60 
    madeClick2,...
    madeClick3,...
    et_good_check,...
    et_null_check,...
    et_total_check,... 65
    practice,...
    minDistanceIndex,...
    testingRoom};
end

%% RECORD ET DATA TO .MAT FILE
if ETconnected
    cd data/ET
    save(matETfile_name,'mx','my','ma','matETttrial','matETtblock'); 
    cd ..; cd ..
end

 
