%% Timing relative 
drawFixTimeRel = drawFixTime - trialStartTime;
startedFixTimerRel = startedFixTimer - drawFixTime;
drawMemCueTimeRel = drawMemCueTime - startedFixTimer;
remMemCueTimeRel = remMemCueTime - drawMemCueTime;
drawSacTimeRel = drawSacTime - remMemCueTime;
waitFixTimeRel = waitFixTime - drawSacTime;
drawMemTestRel = drawMemTest - waitFixTime;
drawMasksRel = drawMasks - drawMemTest;
remMasksRel = remMasks - drawMasks;
startReportRel = startReport - remMasks;
madeClick3Rel = madeClick3 - madeClick2;
madeClick2Rel = madeClick2 - madeClick1;
madeClick1Rel = madeClick1 - startReport;

%% DATE
Date = datestr(date);
dt = datestr(now, 'mmmm dd, yyyy HH:MM:SS.FFF');

%% ASSIGN ET PARAMETERS IF NO ET
if ~ETconnected
    sac_duration = NaN;
    prefix_duration = NaN; 
    prefix_execution = NaN;
    sac_execution = NaN;
    et_good_check = NaN;
    et_null_check = NaN;
    et_total_check = NaN;
end

Results(grandTrial,:) = {...
    dt,...1
    subj_init,... 2
    subj_num,...  
    block,... 
    trial,...
    grandTrial,...   
    saccade,...
    retino,...
    firstFix',... 
    newFix',...   
    position,...
    memCueLoc,... 
    ffPos,... 
    nfPos,... 
    cueDist2ff,...
    cueDist2nf,... 
    PPD,...
    DPP,... 
    testColor,...
    reportedcolor,...
    col_diff,...
    confValues,...
    confValues2,...
    startingcolor,...
    randrotate,...
    flip,...
    asymmetric,...
    trialStartTime,...  
    drawFixTimeRel,...
    startedFixTimerRel,...
    drawMemCueTimeRel,... 
    remMemCueTimeRel,...
    drawSacTimeRel,...
    waitFixTimeRel,...
    drawMemTestRel,... 
    drawMasksRel,...
    remMasksRel,...35
    startReportRel,...
    madeClick1Rel,...
    madeClick2Rel,...38
    madeClick3Rel,...
    prefix_execution,...  40
    prefix_duration,... 
    sac_execution,...42
    sac_duration,...
    et_good_check,...44
    et_null_check,...
    et_total_check,...46
    practice};

%% RECORD ET DATA TO .MAT FILE
if ETconnected
    cd data/ET
    save(matETfile_name,'mx','my','ma','matETttrial','matETtblock'); 
    cd ..; cd ..
end

 
